### ISSUE TITLE
Improve git flow

### ISSUE THREAD

**Issue by albi005** [kir-dev/cmsch#813]
## Deployment

AFAICT, currently there are no release branches for specific deployments so we could switch to a flow where stable versions are marked by tagging commits on the main branch. 
We could create a GitHub Action that runs when a new tag is created and would deploy to the GitHub container registry.  After that, every deployment could automatically pull updates using [watchtower](https://containrrr.dev/watchtower/).

Alternatively, instead of tags, we could just have the action be triggered manually, or even on every push to main.
 
I use the flow with tags [here](https://github.com/albi005/MaterialColorUtilities/releases), where a new nuget package is published when creating a new release, thereby creating a new tag. ([workflow file](https://github.com/albi005/MaterialColorUtilities/blob/47eddfb561e279264ec3284a61d78335cf324bb1/.github/workflows/ci.yml#L49))

**Tasks**
- [ ] Rename staging to main
- [ ] Delete master
- [x] ~~(optional) Create a [ruleset](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) for `v*` tags~~

## Merging
I don't like that pull request information, for example, which commits belong together, is lost by using [rebase and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits). My suggestion is to keep pull requests small and use [squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) .

**Tasks**
- [ ] Disallow *rebase and merge* and allow *squash and merge*
## Main branch
It's way too easy to accidentally push changes to main/staging.

**Tasks**
- [ ] Disallow pushing to main
    - Repo settings > Rules
        - Default branch
        - Require a pull request before merging
        - Block force pushes

## Sources
- [GitHub flow](https://docs.github.com/en/get-started/using-github/github-flow)
- [A successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/)
- merge strategy examples:
	- squash:
		- https://github.com/dotnet/aspnetcore/commits/main/
		- https://github.com/charmbracelet/gum/commits/main/
		- https://github.com/rustic-rs/rustic/commits/main/
	- merge commit:
		- https://github.com/phiresky/ripgrep-all/commits/master/
		- https://github.com/NixOS/nixpkgs/commits/master/
		- https://github.com/torvalds/linux/commits/master/
		- https://github.com/restic/restic/commits/master/
		- https://github.com/rustic-rs/rustic/commits/main/  (before 2023.08.)

**Comment by albi005** [comment]
Do we want versioning and releases?
